hamburger = int(450)
sheikh = int(200)
cola = int(100)
taxfree = (hamburger + sheikh + cola)
tax = taxfree * 0.1
tip = taxfree * 0.16
total = (taxfree + tax + tip)
hamburger = str(hamburger)
sheikh = str(sheikh)
cola = str(cola)
taxfree = str(taxfree)
tax = str(tax)
tip = str(tip)
total = str(total)
print('ハンバーガー' + '\t:' + hamburger )
print('シェイク' + '\t:' + sheikh )
print('コーラ' + '\t:' + cola )
print('合計額(税抜)' + '\t:' + taxfree )
print('消費税' + '\t:' + tax )
print('チップ' + '\t:' + tip )
print('合計額(税込)' + '\t:' + total )
